--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/TheFixerDevelopment/NoFallDamage
branches:
- patch-1
projects:
  NoFallDamagePE:
    path: Unknown_v1 (2)/
  NoFallDamage:
    path: ""
...
